"""empty message

Revision ID: 3052e43adcb9
Revises: 3cb95787f47b
Create Date: 2021-05-21 15:34:06.104620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3052e43adcb9'
down_revision = '3cb95787f47b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qa_answer', sa.Column('desc', sa.String(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qa_answer', 'desc')
    # ### end Alembic commands ###
