"""empty message

Revision ID: 3cb95787f47b
Revises: 6414a5a1c1d6
Create Date: 2021-05-19 16:53:57.809197

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3cb95787f47b'
down_revision = '6414a5a1c1d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts_user', 'status',
               existing_type=mysql.SMALLINT(),
               comment=None,
               existing_comment='1是允许登录,0是不能登录',
               existing_nullable=True)
    op.alter_column('accounts_user', 'is_super',
               existing_type=mysql.SMALLINT(),
               comment=None,
               existing_comment='权限分配',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts_user', 'is_super',
               existing_type=mysql.SMALLINT(),
               comment='权限分配',
               existing_nullable=True)
    op.alter_column('accounts_user', 'status',
               existing_type=mysql.SMALLINT(),
               comment='1是允许登录,0是不能登录',
               existing_nullable=True)
    # ### end Alembic commands ###
