"""empty message

Revision ID: ab0e68e649d5
Revises: b5c69be3dd58
Create Date: 2021-06-01 09:57:14.079730

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ab0e68e649d5'
down_revision = 'b5c69be3dd58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qa_answer', 'desc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qa_answer', sa.Column('desc', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=256), nullable=True))
    # ### end Alembic commands ###
