"""empty message

Revision ID: b2fc53103882
Revises: b935c0bd05ad
Create Date: 2021-06-13 13:48:12.946717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2fc53103882'
down_revision = 'b935c0bd05ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qa_question_follow',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('q_id', sa.Integer(), nullable=True),
    sa.Column('is_valid', sa.SmallInteger(), nullable=True, comment='逻辑删除'),
    sa.Column('followed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['q_id'], ['qa_question.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['accounts_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qa_answer_dislove',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('answer_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('dislove_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['qa_answer.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['qa_question.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['accounts_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qa_answer_dislove')
    op.drop_table('qa_question_follow')
    # ### end Alembic commands ###
