"""empty message

Revision ID: b5c69be3dd58
Revises: 3052e43adcb9
Create Date: 2021-05-31 19:53:30.112863

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b5c69be3dd58'
down_revision = '3052e43adcb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('qa_answer', 'desc',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=256),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('qa_answer', 'desc',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=256),
               nullable=False)
    # ### end Alembic commands ###
