"""empty message

Revision ID: b935c0bd05ad
Revises: ab0e68e649d5
Create Date: 2021-06-08 09:29:06.355482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b935c0bd05ad'
down_revision = 'ab0e68e649d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts_user_profile', sa.Column('follow', sa.Integer(), nullable=True))
    op.add_column('accounts_user_profile', sa.Column('fans', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts_user_profile', 'fans')
    op.drop_column('accounts_user_profile', 'follow')
    # ### end Alembic commands ###
